name = "ebook"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "ebook-library-db"
database_id = "79929b7e-e5e1-412b-a231-a2bb210b759f"

[vars]
ALLOW_REGISTRATION = "true"
INVITE_CODE = "nikunj2024"
JWT_SECRET_KEY = "local-dev-secret-change-in-production"
